version: '2'
services:
  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  app:
    image: app
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres